const products = [
  {
    id: 1,
    imgSrc: '../../img/ps-5.png',
    imgss_1: '../../img/ps-5.png',
    imgss_2: '../../img/ps5-s2.png',
    imgss_3: '../../img/ps5-s3.png',
    title: 'Sony Playstation 5',
    description: 'Playstation 5 With Controller',
    price: 1000,
    rating: 5,
    brand: 'Sony',
    category: '<i class="bi bi-controller"></i> Gaming Console'
  },
  {
    id: 2,
    imgSrc: '../../img/ps-3.png',
    imgss_1: '../../img/ps-5.png',
    imgss_2: '../../img/ps5-s2.png',
    imgss_3: '../../img/ps5-s3.png',
    title: 'Sony Playstation 3',
    description: 'Playstation 3 With Controller',
    price: 1000,
    rating: 4,
    brand: 'Sony',
    category: '<i class="bi bi-controller"></i> Gaming Console'
  },
  {
    id: 3,
    imgSrc: '../../img/camera-1.png',
    imgss_1: '../../img/canon-1.jpg',
    imgss_2: '../../img/canon-2.jpg',
    imgss_3: '../../img/canon-3.jpg',
    title: 'Canon 1200D',
    description: 'Camera with one lens and battery',
    price: 1000,
    rating: 5,
    brand: 'Canon',
    category: '<i class="bi bi-camera"></i> Camera'
  },
  {
    id: 4,
    imgSrc: '../../img/camera-2.png',
    imgss_1: '../../img/nikon-1.jpg',
    imgss_2: '../../img/nikon-2.jpg',
    imgss_3: '../../img/nikon-3.jpg',
    title: 'Nikon D5600',
    description: 'Camera with one lens and battery',
    price: 1000,
    rating: 4,
    brand: 'Nikon',
    category: '<i class="bi bi-camera"></i> Camera'
  },
  {
    id: 5,
    imgSrc: '../../img/calc-1.png',
    imgss_1: '../../img/calc-1-1.jpg',
    imgss_2: '../../img/calc-2-2.jpg',
    imgss_3: '../../img/calc-3-3.jpg',
    title: 'Casio Scientific Calculator',
    description: 'Casio Scientific calculator',
    price: 1000,
    rating: 5,
    brand: 'Casio',
    category: '<i class="bi bi-calculator"></i> Calculator'
  },
  {
    id: 6,
    imgSrc: '../../img/cycle-1.png',
    imgss_1: '../../img/cycle-1.jpg',
    imgss_2: '../../img/cycle-2.jpg',
    imgss_3: '../../img/cycle-3.jpg',
    title: 'Hero Bicycle 7 gear',
    description: 'Hero bicycle for rent',
    price: 1000,
    rating: 5,
    brand: 'Hero',
    category: '<i class="bi bi-bicycle"></i> Bicycle'
  },
  {
    id: 7,
    imgSrc: '../../img/cycle-2.png',
    imgss_1: '../../img/cycle-4.jpg',
    imgss_2: '../../img/cycle-5.jpg',
    imgss_3: '../../img/cycle-6.jpg',
    title: 'Hero Bicycle 7 gear',
    description: 'Hero bicycle for rent',
    price: 1000,
    rating: 4,
    brand: 'Hero',
    category: '<i class="bi bi-bicycle"></i> Bicycle'
  },
  {
    id: 8,
    imgSrc: '../../img/speaker-3.png',
    imgss_1: '../../img/sony-speaker-1.jpeg',
    imgss_2: '../../img/sony-speaker-2.jpeg',
    imgss_3: '../../img/sony-speaker-3.jpeg',
    title: 'Sony 97898',
    description: 'Speaker with equipment',
    price: 1000,
    rating: 3,
    brand: 'Sony',
    category: '<i class="bi bi-speaker"></i> Speaker'
  },
  {
    id: 9,
    imgSrc: '../../img/dell-2.jpg',
    imgss_1: '../../img/dell-1.jpg',
    imgss_2: '../../img/dell-2.jpg',
    imgss_3: '../../img/dell-3.jpg',
    title: 'Dell Inspiron 15',
    description: 'Dell Inspiron 15 with 16GB RAM',
    price: 1500,
    rating: 4,
    brand: 'Dell',
    category: '<i class="bi bi-laptop"></i> Laptop'
  },
  {
    id: 10,
    imgSrc: '../../img/macbook-.jpeg',
    imgss_1: '../../img/macbook-.jpeg',
    imgss_2: '../../img/macbook-1.jpeg',
    imgss_3: '../../img/macbook-2.jpeg',
    title: 'MacBook Pro',
    description: 'MacBook Pro 16-inch with M1 chip',
    price: 2500,
    rating: 5,
    brand: 'Apple',
    category: '<i class="bi bi-laptop"></i> Laptop'
  },
  {
    id: 11,
    imgSrc: '../../img/ipad-1.jpeg',
    imgss_1: '../../img/ipad-1.jpeg',
    imgss_2: '../../img/ipad-2.jpeg',
    imgss_3: '../../img/ipad-3.jpeg',
    title: 'iPad Air',
    description: 'Apple iPad Air with 64GB storage',
    price: 600,
    rating: 4,
    brand: 'Apple',
    category: '<i class="bi bi-tablet"></i> Tablet'
  },
  {
    id: 12,
    imgSrc: '../../img/samsung-1.jpg',
    imgss_1: '../../img/samsung-1.jpg',
    imgss_2: '../../img/samsung-2.jpg',
    imgss_3: '../../img/samsung-3.jpg',
    title: 'Samsung Galaxy S21',
    description: 'Samsung Galaxy S21 with 128GB storage',
    price: 800,
    rating: 4,
    brand: 'Samsung',
    category: '<i class="bi bi-phone"></i> Smartphone'
  },
  {
    id: 13,
    imgSrc: '../../img/watch-6.jpg',
    imgss_1: '../../img/watch-6.jpg',
    imgss_2: '../../img/watch-6-2.jpg',
    imgss_3: '../../img/watch-6-3.jpeg',
    title: 'Apple Watch Series 6',
    description: 'Apple Watch Series 6 with GPS',
    price: 400,
    rating: 5,
    brand: 'Apple',
    category: '<i class="bi bi-watch"></i> Smartwatch'
  },
  {
    id: 14,
    imgSrc: '../../img/samsung-led-1.jpeg',
    imgss_1: '../../img/samsung-led-1.jpeg',
    imgss_2: '../../img/samsung-led-2.jpeg',
    imgss_3: '../../img/samsung-led-3.jpeg',
    title: 'Samsung QLED TV',
    description: 'Samsung 55-inch QLED TV',
    price: 1200,
    rating: 5,
    brand: 'Samsung',
    category: '<i class="bi bi-tv"></i> Television'
  },
  {
    id: 15,
    imgSrc: '../../img/sony-headphones-2.jpg',
    imgss_1: '../../img/sony-headphones-1.jpg',
    imgss_2: '../../img/sony-headphones-2.jpg',
    imgss_3: '../../img/sony-headphones-3.jpg',
    title: 'Sony WH-1000XM4',
    description: 'Sony Noise Cancelling Headphones',
    price: 350,
    rating: 5,
    brand: 'Sony',
    category: '<i class="bi bi-headphones"></i> Headphones'
  }
];
