const products = [
  {
    id: 1,
    imgSrc: '../../img/ps5-s1.png',
    imgss_1: '../../img/ps5-s1.png',
    imgss_2: '../../img/ps5-s2.png',
    imgss_3: '../../img/ps5-s3.png',
    title: 'Sony PlayStation®5 ',
    description: 'PlayStation®5 Console The PS5® console unleashes new gaming possibilities that you never anticipated. Experience lightning fast loading with an ultra-high speed SSD, deeper immersion with support for haptic feedback, adaptive triggers, and 3D Audio, and an all-new generation of incredible PlayStation® games. Lightning Speed: Harness the power of a custom CPU, GPU, and SSD with Integrated I/O that rewrite the rules of what a PlayStation® console can do. Stunning Games: Marvel at incredible graphics and experience new PS5® features. Play a back catalog of supported PS4® games. Breathtaking Immersion: Discover a deeper gaming experience with support for haptic feedback, adaptive triggers, and 3D Audio technology. Vertical stand sold separately. *PS5® console (CFI-2000 model group – slim) 23D audio via built-in TV speakers or analog/USB stereo headphones. Set up and latest system software update required. Internet connection required to pair Disc Drive and PS5® console upon setup.',
    price: 1000,
    rating: 5,
    brand: 'Sony',
    category: '<i class="bi bi-controller"></i> Gaming Console'
  },
  {
    id: 3,
    imgSrc: '../../img/canon-1.jpg',
    imgss_1: '../../img/canon-1.jpg',
    imgss_2: '../../img/canon-2.jpg',
    imgss_3: '../../img/canon-3.jpg',
    title: 'Canon EOS 1500D 24.1MP',
    description: 'Unlock boundless creativity on your journeys with Canon EOS R10. Compact design, 24.2MP clarity, swift autofocus, and 4K UHD video redefine travel and vlogging adventures, capturing every moment in vivid detail and unmatched brilliance.',
    price: 1000,
    rating: 5,
    brand: 'Canon',
    category: '<i class="bi bi-camera"></i> Camera'
  },
  {
    id: 4,
    imgSrc: '../../img/nikon-1.jpg',
    imgss_1: '../../img/nikon-1.jpg',
    imgss_2: '../../img/nikon-2.jpg',
    imgss_3: '../../img/nikon-3.jpg',
    title: 'Nikon Z50 Mirrorless Camera',
    description: 'Introducing the Z 50, a compact, lightweight, and powerful mirrorless camera. Inheriting the proud DNA of the Z series, this camera features a large inner diameter of 55mm and a short flange focal distance of 16mm – delivering incredibly vibrant images and three-dimensionality without the little imperfections. Capture spontaneous life moments with the intuitively-designed and comfortable camera body that feels like an extension of your hand. It is almost as nimble and compact in size as your passport – though not as thin! Perfect for adventurers, wanderers, foodies and café-dwellers, slip the Z 50 into your bag the next time you go exploring and share your experiences with the world.',
    price: 1000,
    rating: 4,
    brand: 'Nikon',
    category: '<i class="bi bi-camera"></i> Camera'
  },
  {
    id: 5,
    imgSrc: '../../img/cal-1-1.jpg',
    imgss_1: '../../img/cal-1-1.jpg',
    imgss_2: '../../img/cal-2-2.jpg',
    imgss_3: '../../img/cal-3-3.jpg',
    title: 'Casio FX-82MS 2nd Gen',
    description: '2nd edition comes with same features and new sleek design with curved edges which makes it compact and easy to carryTrigonometrical, Logarithmic, Permutation, Combination and many other mathematical Functions',
    price: 1000,
    rating: 5,
    brand: 'Casio',
    category: '<i class="bi bi-calculator"></i> Calculator'
  },
  {
    id: 6,
    imgSrc: '../../img/cycle-1.jpg',
    imgss_1: '../../img/cycle-1.jpg',
    imgss_2: '../../img/cycle-2.jpg',
    imgss_3: '../../img/cycle-3.jpg',
    title: 'Hero Sprint Riot 26T ',
    description: 'Hero Riot -Single Speed, Brakes: Front & Rear 160 mm mechanical disc brakes, Saddle: MTB style with Quick release, Pedals: Anti-Skid Pedals with Reflectors, Ideal Rider Height: 5 feet 2 inch -5 feet 8 inch, Ideal weight: upto 100 kg, Ideal Age Group: 12+ Years',
    price: 1000,
    rating: 5,
    brand: 'Hero',
    category: '<i class="bi bi-bicycle"></i> Bicycle'
  },
  {
    id: 7,
    imgSrc: '../../img/cycle-4.jpg',
    imgss_1: '../../img/cycle-4.jpg',
    imgss_2: '../../img/cycle-5.jpg',
    imgss_3: '../../img/cycle-6.jpg',
    title: 'Hero Sprint Mens Frame Santiago ',
    description: 'Hero Sprint Mens Frame Santiago 26T SS Hybrid Bike (White, 18 Inches, SSAN26WHWH01HM)',
    price: 1000,
    rating: 4,
    brand: 'Hero',
    category: '<i class="bi bi-bicycle"></i> Bicycle'
  },
  {
    id: 8,
    imgSrc: '../../img/samsung-led-1.jpeg',
    imgss_1: '../../img/samsung-led-1.jpeg',
    imgss_2: '../../img/samsung-led-2.jpg',
    imgss_3: '../../img/samsung-led-3.jpeg',
    title: 'Samsung 138 cm (55 inches) ',
    description: 'Resolution : QLED | 4K Ultra HD (3840 x 2160) | Refresh Rate : 120 Hertz;Connectivity : 4 HDMI ports to connect set top box or gaming console | 2 USB ports to connect hard drives or other USB devices | Ethernet | Wi-fi | Bluetooth Sound: 60W Output- 4.2.2CH | Powerful Speakers with Dolby Atmos | Q-Symphony | Woofer | Active Voice Amplifier | OTS+ | Adaptive Sound+ | Dual Audio Support (Bluetooth) | Buds Auto Switch',
    price: 1200,
    rating: 5,
    brand: 'Samsung',
    category: '<i class="bi bi-tv"></i> Television'
  },
  {
    id: 9,
    imgSrc: '../../img/dell-1.jpg',
    imgss_1: '../../img/dell-1.jpg',
    imgss_2: '../../img/dell-2.jpg',
    imgss_3: '../../img/dell-3.jpg',
    title: 'Dell Inspiron 15 Laptop, Intel Core',
    description: 'Dell 15 Thin & Light Laptop, 12th Gen Intel Core i5-1235U Processor, 8GB, 512GB SSD, 15.6" (39.62cm) FHD Display, Win 11 + MSO21, 15 Month McAfee Antivirus, Black, Spill-Resistant Keyboard,1.66kg',
    price: 1500,
    rating: 4,
    brand: 'Dell',
    category: '<i class="bi bi-laptop"></i> Laptop'
  },
  {
    id: 10,
    imgSrc: '../../img/macbook-.jpeg',
    imgss_1: '../../img/macbook-.jpeg',
    imgss_2: '../../img/macbook-1.jpeg',
    imgss_3: '../../img/macbook-2.jpeg',
    title: 'Apple 2024 MacBook Air 13',
    description: 'Apple 2024 MacBook Air 13″ Laptop with M3 chip: 34.46 cm (13.6″) Liquid Retina Display, 8GB Unified Memory, 256GB SSD Storage, Backlit Keyboard, 1080p FaceTime HD Camera, Touch ID- Silver',
    price: 2500,
    rating: 5,
    brand: 'Apple',
    category: '<i class="bi bi-laptop"></i> Laptop'
  },
  {
    id: 11,
    imgSrc: '../../img/ipad-1.jpeg',
    imgss_1: '../../img/ipad-1.jpeg',
    imgss_2: '../../img/ipad-2.jpeg',
    imgss_3: '../../img/ipad-3.jpeg',
    title: 'Apple iPad Air 11″ (M2):',
    description: 'Apple iPad Air 11″ (M2): Liquid Retina Display, 128GB, Landscape 12MP Front Camera / 12MP Back Camera, Wi-Fi 6E, Touch ID, All-Day Battery Life — Space Grey',
    price: 600,
    rating: 4,
    brand: 'Apple',
    category: '<i class="bi bi-tablet"></i> Tablet'
  },
  {
    id: 12,
    imgSrc: '../../img/samsung-1.jpg',
    imgss_1: '../../img/samsung-1.jpg',
    imgss_2: '../../img/samsung-2.jpg',
    imgss_3: '../../img/samsung-3.jpg',
    title: 'Samsung Galaxy S24 5G AI ',
    description: 'Easy to grip. Satisfying to hold. With their unified design and satin finish, Galaxy S24 feels as smooth as it looks.Theyre the upgrades you ve waited for. More screen. More battery. More processing power. Theres so much more to love about Galaxy S24.A true pixel powerhouse that will not disappoint. Ever. Snap high-res pics for that will no doubt withstand the test of time for years to come. Search like never before with Circle to Search. Simply trace an object to get Google Search results. Its a new visual way to find what youre looking for.quick language translation on your next phone call. Thats right, AI helps you communicate outside your own language while you talk on the phone. And get this, it even works on messaging.',
    price: 800,
    rating: 4,
    brand: 'Samsung',
    category: '<i class="bi bi-phone"></i> Smartphone'
  },
  {
    id: 13,
    imgSrc: '../../img/watch-6.jpg',
    imgss_1: '../../img/watch-6.jpg',
    imgss_2: '../../img/watch-6-2.jpg',
    imgss_3: '../../img/watch-6-3.jpg',
    title: 'Apple Watch Series 6',
    description: 'Apple New Watch Series 6 (GPS + Cellular, 40mm) - Graphite Stainless Steel Case with Black Sport Band',
    price: 400,
    rating: 5,
    brand: 'Apple',
    category: '<i class="bi bi-watch"></i> Smartwatch'
  },
  {
    id: 14,
    imgSrc: '../../img/sony-speaker-1.jpeg',
    imgss_1: '../../img/sony-speaker-1.jpeg',
    imgss_2: '../../img/sony-speaker-2.jpeg',
    imgss_3: '../../img/sony-speaker-3.jpeg',
    title: 'Sony SRS-XB100 Wireless Bluetooth',
    description: 'Sony SRS-XB100 Wireless Bluetooth Portable Lightweight Super Compact Travel Speaker, Extra Durable IP 67 Waterproof & Dustproof, 16 Hrs Batt, Versatile Strap, Extra Bass & Hands-Free Calling Orange',
    price: 1000,
    rating: 3,
    brand: 'Sony',
    category: '<i class="bi bi-speaker"></i> Speaker'
  },
  {
    id: 15,
    imgSrc: '../../img/sony-headphones-1.jpg',
    imgss_1: '../../img/sony-headphones-1.jpg',
    imgss_2: '../../img/sony-headphones-2.jpg',
    imgss_3: '../../img/sony-headphones-3.jpg',
    title: 'Sony WH-1000XM4',
    description: 'Sony WH-CH520, Wireless On-Ear Bluetooth Headphones with Mic, upto 50 Hours Playtime, DSEE Upscale, Multipoint Connectivity/Dual Pairing,Voice Assistant App Support for Mobile Phones (Black)',
    price: 350,
    rating: 5,
    brand: 'Sony',
    category: '<i class="bi bi-headphones"></i> Headphones'
  }
];



